# Generated by Django 5.2 on 2025-05-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
