# Generated by Django 5.2 on 2025-06-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
