# Generated by Django 5.2 on 2025-06-05 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konkurs.competition'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konkurs.participant'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
