# Generated by Django 5.2 on 2025-06-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0002_participant_is_paid'),
        ('payment', '0002_alter_purchasemodel_competition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='konkurs.competition'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='konkurs.participant'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
