# Generated by Django 5.2 on 2025-05-21 19:53

import authentication.utils
import authentication.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[authentication.validators.validate_uz_phone_number_for_model])),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, validators=[authentication.validators.validate_name_for_model])),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, validators=[authentication.validators.validate_name_for_model])),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, validators=[authentication.validators.validate_name_for_model])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('speciality', models.CharField(blank=True, max_length=300)),
                ('speciality_uz', models.CharField(blank=True, max_length=300, null=True)),
                ('speciality_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('speciality_en', models.CharField(blank=True, max_length=300, null=True)),
                ('academic_degree', models.IntegerField(choices=[(0, '---'), (1, 'Associate'), (2, 'Bachelor'), (3, 'Master'), (4, 'Doctoral')], default=0)),
                ('place_of_work', models.CharField(blank=True, max_length=300)),
                ('place_of_work_uz', models.CharField(blank=True, max_length=300, null=True)),
                ('place_of_work_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('place_of_work_en', models.CharField(blank=True, max_length=300, null=True)),
                ('role', models.IntegerField(choices=[(0, '---'), (1, 'Candidate'), (2, 'Jury'), (3, 'Admin')], default=0)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='media/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlacklistedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPRegisterResend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('otp_code', models.PositiveIntegerField(default=authentication.utils.generate_otp_code)),
                ('otp_type', models.IntegerField(choices=[(0, '---'), (1, 'register'), (2, 'resend')], default=1)),
                ('attempts', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPSetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('otp_code', models.PositiveIntegerField(default=authentication.utils.generate_otp_code)),
                ('otp_token', models.UUIDField(default=uuid.uuid4)),
                ('attempts', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('temp_password', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
