from django.urls import path
from .views import (
    CategoryViewSet,
    CompetitionViewSet,
    JuryViewSet,
    WebSocialMediaViewSet,
    ContactInformationViewSet,
    AboutResultViewSet,
    AboutUsViewSet,
    WebResultImageViewSet,
    ContactUsViewSet,
    PolicyViewSet,
    AdminPaymentViewSet,
)

urlpatterns = [
    # category
    path('get_categories/', CategoryViewSet.as_view({'get': 'get'}), name='get_categories'),
    path('get_all_categories/', CategoryViewSet.as_view({'get': 'get'}), name='get_categories'),
    path('get_category_by_id/<int:pk>/', CategoryViewSet.as_view({'get': 'get_by_id'}), name='get_category_by_id'),
    path('create_category/', CategoryViewSet.as_view({'post': 'create'}), name='create_category'),
    path('update_category/<int:pk>/', CategoryViewSet.as_view({'patch': 'update'}), name='update_category'),
    path('delete_category/<int:pk>/', CategoryViewSet.as_view({'delete': 'delete'}), name='delete_category'),
    # competition
    path('get_participants/<int:pk>/', CompetitionViewSet.as_view({'get': 'participants'}), name='get_participants'),
    path('search_participant/<int:pk>/', CompetitionViewSet.as_view({'get': 'search_participant'}),
         name='search_participant'),  #
    path('get_winners/<int:pk>/', CompetitionViewSet.as_view({'get': 'winners'}), name='get_winners'),
    path('get_winners_for_active/<int:pk>/', CompetitionViewSet.as_view({'get': 'get_exist_winners'}), name='get_winners_for_active'),
    path('search_winners/<int:pk>/', CompetitionViewSet.as_view({'get': 'search_winners'}), name='search_winners'),  #
    path('get_competitions/', CompetitionViewSet.as_view({'get': 'get_comp'}), name='get_competitions'),
    path('search_comp/', CompetitionViewSet.as_view({'get': 'search_comp'}), name='search_comp'),  #
    path('filter_comp/', CompetitionViewSet.as_view({'get': 'filter_comp'}), name='filter_comp'),
    path('get_competition/<int:pk>/', CompetitionViewSet.as_view({'get': 'get_comp_by_id'}),
         name='get_competition_by_id'),
    path('create_competition/', CompetitionViewSet.as_view({'post': 'create_comp'}), name='create_competition'),
    path('get_exist_comp_by_id/<int:pk>/', CompetitionViewSet.as_view({'get': 'get_exist_comp_by_id'}),
         name='get_exist_comp_by_id'),
    path('update_competition/<int:pk>/', CompetitionViewSet.as_view({'patch': 'update_comp'}),
         name='update_competition'),
    path('delete_competition/<int:pk>/', CompetitionViewSet.as_view({'delete': 'delete_comp'}),
         name='delete_competition'),
    path('participant_requests/<int:pk>/', CompetitionViewSet.as_view({'get': 'participants_requests'}),
         name='participant_requests'),
    path('approvement/', CompetitionViewSet.as_view({'post': 'approve'}),
         name='request_action'),
    path('active_participants/<int:pk>/', CompetitionViewSet.as_view({'get': 'active_participants'}),
         name='active_participants'),
    path('create_winners/<int:pk>/', CompetitionViewSet.as_view({'post': 'create_winners'}), name='create_winners'),
    path('update_winners/<int:pk>/', CompetitionViewSet.as_view({'patch': 'update_winners'}), name='update_winners'),
    path('delete_winner/<int:pk>/', CompetitionViewSet.as_view({'delete': 'delete_winner'}), name='delete_winners'),
    path('others/<int:pk>/', CompetitionViewSet.as_view({'get': 'others'}), name='others'),
    path('send_thank_you_message/<int:pk>/', CompetitionViewSet.as_view({'post': 'send_thank_you_message'}),
         name='send_thank_you_message'),
    # jury
    path('get_all_juries/', JuryViewSet.as_view({'get': 'get_all'}), name='get_all_juries'),
    path('search_juries/', JuryViewSet.as_view({'get': 'search_juries'}), name='search_juries'),  #
    path('get_jury_by_id/<int:pk>/', JuryViewSet.as_view({'get': 'get_by_id'}), name='get_by_id'),
    path('create_jury/', JuryViewSet.as_view({'post': 'create'}), name='create_jury'),
    path('get_exist_jury_by_id/<int:pk>/', JuryViewSet.as_view({'get': 'get_exist_jury_by_id'}),
         name='get_exist_jury_by_id'),
    path('update_jury/<int:pk>/', JuryViewSet.as_view({'patch': 'update'}), name='update_jury'),
    path('delete_jury/<int:pk>/', JuryViewSet.as_view({'delete': 'delete'}), name='delete_jury'),
    # dynamic
    # Social media
    path('get_social_media_by_id/<int:pk>/', WebSocialMediaViewSet.as_view({'get': 'get_by_id'}),
         name='get_social_media_by_id'),
    path('get_all_social_media/', WebSocialMediaViewSet.as_view({'get': 'get_all'}), name='get_all_social_media'),
    path('create_social_media/', WebSocialMediaViewSet.as_view({'post': 'create'}), name='create_social_media'),
    path('update_social_media/<int:pk>/', WebSocialMediaViewSet.as_view({'patch': 'update'}),
         name='update_social_media'),
    path('delete_social_media/<int:pk>/', WebSocialMediaViewSet.as_view({'delete': 'delete'}),
         name='delete_social_media'),
    # Contact info
    path('get_contact_info_by_id/<int:pk>/', ContactInformationViewSet.as_view({'get': 'get_by_id'}),
         name='get_contact_info_by_id'),
    path('get_all_contact_info/', ContactInformationViewSet.as_view({'get': 'get_all'}), name='get_all_contact_info'),
    path('create_contact_info/', ContactInformationViewSet.as_view({'post': 'create'}), name='create_contact_info'),
    path('get_exist_contact_info_by_id/<int:pk>/',
         ContactInformationViewSet.as_view({'get': 'get_exist_contact_info_by_id'}),
         name='get_exist_contact_info_by_id'),
    path('update_get_contact_info/<int:pk>/', ContactInformationViewSet.as_view({'patch': 'update'}),
         name='update_get_contact_info'),
    path('delete_contact_info_by_id/<int:pk>/', ContactInformationViewSet.as_view({'delete': 'delete'}),
         name='delete_contact_info_by_id'),
    # About Res
    path('get_about_result_by_id/<int:pk>/', AboutResultViewSet.as_view({'get': 'get_by_id'}),
         name='get_about_result_by_id'),
    path('get_all_about_result/', AboutResultViewSet.as_view({'get': 'get_all'}), name='get_all_about_result'),
    path('create_about_result/', AboutResultViewSet.as_view({'post': 'create'}), name='create_about_result'),
    path('get_exist_about_result_by_id/<int:pk>/', AboutResultViewSet.as_view({'get': 'get_exist_about_result_by_id'}),
         name='get_exist_about_result_by_id'),
    path('update_about_result/<int:pk>/', AboutResultViewSet.as_view({'patch': 'update'}),
         name='update_about_result'),
    path('delete_about_result/<int:pk>/', AboutResultViewSet.as_view({'delete': 'delete'}),
         name='delete_about_result'),
    # About Us
    path('get_about_us_by_id/<int:pk>/', AboutUsViewSet.as_view({'get': 'get_by_id'}),
         name='get_about_us_by_id'),
    path('get_all_about_us/', AboutUsViewSet.as_view({'get': 'get_all'}), name='get_all_about_us'),
    path('create_about_us/', AboutUsViewSet.as_view({'post': 'create'}), name='create_about_us'),
    path('get_exist_about_us_by_id/<int:pk>/', AboutUsViewSet.as_view({'get': 'get_exist_about_us_by_id'}),
         name='get_exist_about_us_by_id'),
    path('update_about_us/<int:pk>/', AboutUsViewSet.as_view({'patch': 'update'}),
         name='update_about_us'),
    path('delete_about_us/<int:pk>/', AboutUsViewSet.as_view({'delete': 'delete'}),
         name='delete_about_us'),
    # Policy
    path('get_policy_by_id/<int:pk>/', PolicyViewSet.as_view({'get': 'get_by_id'}),
         name='get_policy_by_id'),
    path('get_all_policy/', PolicyViewSet.as_view({'get': 'get_all'}), name='get_all_policy'),
    path('create_policy/', PolicyViewSet.as_view({'post': 'create'}), name='create_policy'),
    path('get_exist_policy_by_id/<int:pk>/', PolicyViewSet.as_view({'get': 'get_exist_policy_by_id'}),
         name='get_exist_policy_by_id'),
    path('update_policy/<int:pk>/', PolicyViewSet.as_view({'patch': 'update'}),
         name='update_policy'),
    path('delete_policy/<int:pk>/', PolicyViewSet.as_view({'delete': 'delete'}),
         name='delete_policy'),
    # Result Img
    path('get_result_img_by_id/<int:pk>/', WebResultImageViewSet.as_view({'get': 'get_by_id'}),
         name='get_result_img_by_id'),
    path('get_all_result_img/', WebResultImageViewSet.as_view({'get': 'get_all'}), name='get_all_result_img'),
    path('create_result_img/', WebResultImageViewSet.as_view({'post': 'create'}), name='create_result_img'),
    path('update_result_img/<int:pk>/', WebResultImageViewSet.as_view({'patch': 'update'}),
         name='update_result_img'),
    path('delete_result_img/<int:pk>/', WebResultImageViewSet.as_view({'delete': 'delete'}),
         name='delete_result_img'),
    # Contact Us
    path('get_contact_us_by_id/<int:pk>/', ContactUsViewSet.as_view({'get': 'get_by_id'}),
         name='get_contact_us_by_id'),
    path('get_all_contact_us/', ContactUsViewSet.as_view({'get': 'get_all'}), name='get_all_contact_us'),
    path('update_contact_us/<int:pk>/', ContactUsViewSet.as_view({'patch': 'update'}),
         name='update_contact_us'),
    path('delete_contact_us/<int:pk>/', ContactUsViewSet.as_view({'delete': 'delete'}), name='delete_contact_us'),
    # purchase
    path('get_all_purchase/', AdminPaymentViewSet.as_view({'get': 'get'}), name='get_all_purchase'),
]
